### ISSUE TITLE
Block color sampler breaks EMI/REI's Create bulk washing support

### ISSUE THREAD

**Issue by oqtist** [b3spectacled/modern-beta-fabric#112]
When enabled alongside Create and EMI/REI, the renderer in the recipe viewer seems to get confused and either fails to render the recipe or crashes. This happens specifically with bulk washing.

_An excerpt from the logs:_

> [13:49:18] [Render thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1920.method_23752(net.minecraft.class_2338, net.minecraft.class_6539)" because "$$0" is null
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1163.method_4965(class_1163.java:14)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1163.method_4961(class_1163.java:26)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at mod.bespectacled.modernbeta.client.color.BlockColorSampler.getWaterColor(BlockColorSampler.java:109)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at mod.bespectacled.modernbeta.client.color.BlockColors.lambda$register$4(BlockColors.java:42)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_324.method_1697(class_324.java:123)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockModelRenderBuilder.renderModel(GuiGameElement.java:196)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockStateRenderBuilder.renderModel(GuiGameElement.java:236)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockModelRenderBuilder.render(GuiGameElement.java:187)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockStateRenderBuilder.render(GuiGameElement.java:216)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.compat.emi.recipes.fan.FanWashingEmiRecipe.renderAttachedBlock(FanWashingEmiRecipe.java:23)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at com.simibubi.create.compat.emi.CreateEmiAnimations.lambda$addFan$6(CreateEmiAnimations.java:317)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.api.widget.DrawableWidget.method_25394(DrawableWidget.java:44)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at dev.emi.emi.screen.RecipeScreen.method_25394(RecipeScreen.java:225)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_47413(class_437.java:110)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:945)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1219)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:802)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:250)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
> [13:49:18] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

_And the stacktrace from the crash:_

> 	at net.minecraft.class_1163.method_4965(class_1163.java:14)
> 	at net.minecraft.class_1163.method_4961(class_1163.java:26)
> 	at mod.bespectacled.modernbeta.client.color.BlockColorSampler.getWaterColor(BlockColorSampler.java:109)
> 	at mod.bespectacled.modernbeta.client.color.BlockColors.lambda$register$4(BlockColors.java:42)
> 	at net.minecraft.class_324.method_1697(class_324.java:123)
> 	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockModelRenderBuilder.renderModel(GuiGameElement.java:196)
> 	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockStateRenderBuilder.renderModel(GuiGameElement.java:236)
> 	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockModelRenderBuilder.render(GuiGameElement.java:187)
> 	at com.simibubi.create.foundation.gui.element.GuiGameElement$GuiBlockStateRenderBuilder.render(GuiGameElement.java:216)
> 	at com.simibubi.create.compat.rei.category.FanWashingCategory.renderAttachedBlock(FanWashingCategory.java:25)
> 	at com.simibubi.create.compat.rei.category.ProcessingViaFanCategory.draw(ProcessingViaFanCategory.java:68)
> 	at com.simibubi.create.compat.rei.category.CreateRecipeCategory.lambda$setupDisplay$14(CreateRecipeCategory.java:298)
> 	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.DrawableWidget.method_25394(DrawableWidget.java:43)
> 	at me.shedaniel.rei.impl.client.gui.widget.MergedWidget.method_25394(MergedWidget.java:50)
> 	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
> 	at me.shedaniel.rei.api.client.gui.widgets.DelegateWidget.method_25394(DelegateWidget.java:48)
> 	at me.shedaniel.rei.impl.client.gui.widget.DelegateWidgetWithTranslate.method_25394(DelegateWidgetWithTranslate.java:58)
> 	at me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen.method_25394(DefaultDisplayViewingScreen.java:336)
> 	at net.minecraft.class_437.method_47413(class_437.java:110)

**Comment by MuffinTastic** [comment]
I've run into this as well with JEI. Instant crash as soon as I try to view a bulk washing recipe.

**Comment by Yoghurt4C** [comment]
I don't expect this to ever get fixed upstream so you can either [download this build](https://github.com/Yoghurt4C/modern-beta-fabric/releases/tag/homecooked) or do it yourself from [my branch](https://github.com/Yoghurt4C/modern-beta-fabric/tree/1.20.1)
