### ISSUE TITLE
[1.17] Cannot find spawn biome

### ISSUE THREAD

**Issue by RowanSkie** [b3spectacled/modern-beta-fabric#33]
Latest.log: https://paste.ee/p/3mFxZ
crash log:
```
---- Minecraft Crash Report ----
// You're mean.

Time: 08/07/2021, 11:10 am
Description: Exception initializing level

java.lang.NoSuchMethodError: 'void net.minecraft.class_5873.<init>(net.minecraft.class_2794, net.minecraft.class_5539)'
	at com.bespectacled.modernbeta.world.gen.OldChunkGenerator.carve(OldChunkGenerator.java:161)
	at net.minecraft.world.chunk.ChunkStatus.method_16563(ChunkStatus:88)
	at net.minecraft.world.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus:275)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus:231)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage:555)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage:549)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem:58)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:131)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:99)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.bespectacled.modernbeta.world.gen.OldChunkGenerator.method_12108(OldChunkGenerator.java:161)
	at net.minecraft.class_2806.method_16563(class_2806.java:88)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:275)
	at net.minecraft.class_2806.method_12154(class_2806.java:231)
	at net.minecraft.class_3898.method_17225(class_3898.java:555)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:549)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_3900.method_17634(class_3900.java:58)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:131)
	at net.minecraft.class_3846.run(class_3846.java:99)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:405)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:354)
	at net.minecraft.class_1132.method_3823(class_1132.java:71)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 4463457664 bytes (4256 MiB) / 7335837696 bytes (6996 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b06
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28092.99
	Virtual memory used (MB): 19056.27
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 606.05
	JVM Flags: 5 total; -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms640m -Xmx8192m
	Fabric Mods: 
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.0.8
		autopath: Automatic Path 1.4.3
		betterbeds: Better Beds 1.2.0
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.0
		blue_endless_jankson: jankson 1.2.1
		cavebiomes: Cave Biomes 0.6.3
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		craftpresence: CraftPresence 1.8.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		day_dream: Day Dream 1.0.2
		daylight_mobs_reborn: Daylight Mobs Reborn 1.2.2
		dehydration: Dehydration 1.1.6
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dynamicfps: Dynamic FPS 2.0.4
		dynmus: Dynamic Music 1.3.0
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+84310a227d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121d5
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-tree-chopper: Fabric Tree Chopper 0.7.0
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.2+1.17
		fasttransferlib: Fast Transfer Lib 0.4.2
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		hdskins: HD Skins 6.5.0-beta.0.5+ce1b8bd
		hydrogen: Hydrogen 0.3
		imm_ptl_core: Immersive Portals Core 0.8
		immersive_portals: Immersive Portals 0.8
		indium: Indium 1.0.0+rev.820073e
		inventorysorter: Inventory Sorter 1.7.9-1.17
		iris: Iris 1.1.0+rev.7966919
		ironchests: Iron Chests for Fabric 1.0.4
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.9.1
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdabettergrass: LambdaBetterGrass 1.2.0+1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		mavm: More Axolotl Variants Mod 1.0.2b
		megane: megane 5.0.0
		megane-base: megane-base 5.0.0
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.0.0+0.4.2
		megane-runtime: megane-runtime 5.0.0
		megane-team-reborn-energy: megane-team-reborn-energy 5.0.0+0.1.1
		megane-vanilla: megane-vanilla 5.0.0+1.17
		megane-wireless-networks: megane-wireless-networks 5.0.0+1.1.1
		midnightlib: MidnightLib 0.2.2
		minecraft: Minecraft 1.17
		modern_beta: Modern Beta Fabric 2.1.0-1.17.1
		modmenu: Mod Menu 2.0.2
		mostructures: Mo' Structures 1.2.1-1.17
		nethermap: Better Nether Map 1.3.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		omega-config: OmegaConfig 1.0.8
		org_apache_httpcomponents_httpmime: httpmime 4.3.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.8
		repurposed_structures: Repurposed Structures 2.0.6+1.17.1
		roughlyenoughitems: Roughly Enough Items 6.0.251-alpha
		seamless_loading_screen: Seamless Loading Screen 1.3.5+1.17
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		sodium: Sodium 0.3.0+IRIS1-rev.6938090-dirty
		spruceui: SpruceUI 3.2.0+1.17
		stoneholm: Stoneholm 1.3
		team_reborn_energy: Energy 0.1.1
		terra: Terra 5.4.1-BETA+b85880fc
		villagernames: Villager Names 2.0.0
		visualoverhaul: VisualOverhaul 3.3.0
		wirelessnetworks: Wireless Networks 1.1.1
		wthit: wthit 3.6.1
		yungsapi: YUNG's API 1.17-Fabric-11
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	Suspected Mods: Modern Beta Fabric (modern_beta)
```

**Comment by b3spectacled** [comment]
v2.1.0-1.17.1 of the mod is only for Minecraft 1.17.1.  Please update to that version of the game, or use v2.0.0-1.17.

EDIT: Also want to add that this mod conflicts with Hydrogen, due to the way this mod currently handles assigning ocean biomes to bodies of water. You may experience crashes due to that as well. You can either toggle the generateOceans option to off or remove Hydrogen.
