### ISSUE TITLE
crashes with carpet

### ISSUE THREAD

**Issue by jack-mack** [b3spectacled/modern-beta-fabric#54]
[18:20:44] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[18:20:45] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9565 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[18:20:45] [main/INFO]: Loading 41 mods:
	- carpet 1.4.57
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- fabric 0.45.2+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.18.1
	- modern_beta 3.0.3+1.18.1
[18:20:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[18:20:45] [main/INFO]: Compatibility level set to JAVA_16
[18:20:49] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zkj000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[18:20:49] [main/WARN]: @Redirect conflict. Skipping modern_beta.mixins.json:heightprovider.MixinTrapezoidHeightProvider->@Redirect::redirectWarn(Lorg/apache/logging/log4j/Logger;Ljava/lang/String;Ljava/lang/Object;)V from mod modern_beta with priority 1000, already redirected by carpet.mixins.json:TrapezoidHeightProvider_cleanLogsMixin->@Redirect::skipLogs(Lorg/apache/logging/log4j/Logger;Ljava/lang/String;Ljava/lang/Object;)V from mod carpet with priority 1000
[18:20:49] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_6818.<clinit>(class_6818.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_6809.<clinit>(class_6809.java:294) ~[server-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_6342 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6817.<clinit>(class_6817.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_6818.<clinit>(class_6818.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_6809.<clinit>(class_6809.java:294) ~[server-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6817.<clinit>(class_6817.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_6818.<clinit>(class_6818.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_6809.<clinit>(class_6809.java:294) ~[server-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectWarn(Lorg/apache/logging/log4j/Logger;Ljava/lang/String;Ljava/lang/Object;)V in modern_beta.mixins.json:heightprovider.MixinTrapezoidHeightProvider from mod modern_beta failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap modern-beta-fabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_6817.<clinit>(class_6817.java:43) ~[server-intermediary.jar:?]
	at net.minecraft.class_6818.<clinit>(class_6818.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_6809.<clinit>(class_6809.java:294) ~[server-intermediary.jar:?]
	at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more

**Comment by jack-mack** [comment]
ello

**Comment by b3spectacled** [comment]
Sorry about the delay; I'm currently busy with IRL stuff, but will try to get a fix in by 1.18.2.

**Comment by jack-mack** [comment]
yeah sorry for being pushy i just realised i dint upload the full crash log either :p

**Comment by b3spectacled** [comment]
Fixed with 3.0.4, thanks!
