### ISSUE TITLE
Problem with cloth config api.

### ISSUE THREAD

**Issue by stupid759** [b3spectacled/modern-beta-fabric#67]
So i have installed cloth config api, the latest version.

and this appears on fabric loader crash window :

_Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cloth-config2, any version.
Unmet dependency listing:
	 - Mod 'Modern Beta Fabric' (modern_beta) 5.1.1+1.19.3 requires any version of cloth-config2, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)_

**Comment by stupid759** [comment]
![Screenshot 2023-03-03 211805](https://user-images.githubusercontent.com/72989671/222820724-42f2efd2-fa4e-496d-972d-f08853fe304a.png)

**Comment by stupid759** [comment]
wait forge? the thing said fabric on download page!
