### ISSUE TITLE
Fabric Dependency not met even though fabric is installed

### ISSUE THREAD

**Issue by RyanScottClark** [b3spectacled/modern-beta-fabric#68]
Minecraft says that the fabric mod isn't installed even though I have it installed I have tried different versions of fabric. I disabled the mod in multiMC and it loaded and showed fabric was installed. but as soon as I enable modern beta it shows the error.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Modern Beta Fabric' (modern_beta) 5.1.1+1.19.3 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by b3spectacled** [comment]
You need Fabric API: https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by RyanScottClark** [comment]
whoops, sorry I thought that was added automatically.
