### ISSUE TITLE
Freeze in loading screen

### ISSUE THREAD

**Issue by Ameagarinosora** [b3spectacled/modern-beta-fabric#86]
LOGS :

[19:56:00] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.18
[19:56:01] [main/WARN]: Mod resolution failed
[19:56:01] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE modern_beta 6.1+1.19.3 {depends cloth-config2 @ [*]}, ROOT_FORCELOAD_SINGLE modern_beta 6.1+1.19.3]
[19:56:01] [main/INFO]: Reason: [HARD_DEP modern_beta 6.1+1.19.3 {depends cloth-config2 @ [*]}]
[19:56:01] [main/INFO]: Fix: add [add:cloth-config2 1 ([(-∞,∞)])], remove [], replace []
[19:56:01] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cloth-config2, any version.
Unmet dependency listing:
	 - Mod 'Modern Beta Fabric' (modern_beta) 6.1+1.19.3 requires any version of cloth-config2, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.18.jar:?]

**Comment by b3spectacled** [comment]
I think you need to also install Cloth Config.
