### ISSUE TITLE
Mod resolution encountered an incompatible mod set!

### ISSUE THREAD

**Issue by xracecar** [b3spectacled/modern-beta-fabric#93]
The game doesn't boot up and shows this. I have Fabric Loader 0.14.21 installed with Cloth Config 6.2.57, Distant Horizons 1.6.10a, Iris 1.5.2, and Sodium 0.4.9 as other complementary mods.

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Modern Beta Fabric' (modern_beta) 6.1+1.19.3 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by b3spectacled** [comment]
Do you have [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) installed?

**Comment by xracecar** [comment]
No I did not. It finally loaded when I installed it. Kinda weird that it doesn't specify that you need the Fabric API when it only reads "requires any version of fabric, which is missing!"

**Comment by b3spectacled** [comment]
Yes, I find it pretty confusing.
